name: Windows MXE

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows-mxe:
    runs-on: ubuntu-latest
    container:
      image: opensauce04/azahar-build-environment:latest
      options: -u 1001
    env:
      OS: windows
      TARGET: mxe
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive

      - name: Build
        run: ./.ci/mxe.sh

      - name: Pack
        run: ./.ci/pack.sh

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: windows-mxe
          path: artifacts/
